# ========================================================== #
#                      HYPER - RICE                          #
# ========================================================== #

# ========================================================== #
# CONFIGURACION GENERAL                                      #
# ========================================================== #
general {
    lock_cmd            = pidof hyprlock || hyprlock
    before_sleep_cmd    = pidof hyprlock || hyprlock
    after_sleep_cmd     = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# ========================================================== #
# BLOQUEO AUTOMATICO (5 MIN)                                 #
# ========================================================== #
listener {
    timeout    = 300
    on-timeout = pidof hyprlock || hyprlock
}

# ========================================================== #
# APAGADO DE PANTALLA (10 MIN)                               #
# ========================================================== #
listener {
    timeout    = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# ========================================================== #
# SUSPENSION DEL SISTEMA (15 MIN)                            #
# ========================================================== #
listener {
    timeout    = 900
    on-timeout = systemctl suspend
}
